
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Workspace
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed class DataWorkspace : global::Microsoft.LightSwitch.Framework.Base.DataWorkspace<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of a DataWorkspace.  Changes can be made to data sources in the new instance independent of changes made to data sources in the default DataWorkspace.
        /// </summary>
        public DataWorkspace() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the Northwind datasource.  This provides members to query and update data in the data source.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.NorthwindService Northwind
        {
            get
            {
                return global::LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(this, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.Northwind);
            }
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspaceDetails<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.Northwind;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspacePropertySet<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.NorthwindService> Northwind
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.Northwind) as global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.NorthwindService>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.NorthwindService>.Entry
                    Northwind = new global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.NorthwindService>.Entry(
                        "Northwind",
                        global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._Northwind_Stub);
                private static void _Northwind_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataWorkspace.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.NorthwindService>.Data> c, global::LightSwitchApplication.DataWorkspace.DetailsClass d, object sf)
                {
                    c(d, ref d._Northwind, sf);
                }
                 
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.NorthwindService>.Data _Northwind;
            
        }
    
        #endregion
    }
    
    #endregion
    
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the Northwind datasource.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Northwind : global::Microsoft.LightSwitch.Framework.Base.DataService<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// This constructor is used for the internal LightSwitch framework. Use DataWorkspace instead.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Northwind() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the Customers entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Customer> Customers
        {
            get
            {
                return global::LightSwitchApplication.Northwind.DetailsClass.GetValue(this, global::LightSwitchApplication.Northwind.DetailsClass.PropertySetProperties.Customers);
            }
        }
        
        /// <summary>
        /// Gets the Employees entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Employee> Employees
        {
            get
            {
                return global::LightSwitchApplication.Northwind.DetailsClass.GetValue(this, global::LightSwitchApplication.Northwind.DetailsClass.PropertySetProperties.Employees);
            }
        }
        
        /// <summary>
        /// Gets the Products entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Product> Products
        {
            get
            {
                return global::LightSwitchApplication.Northwind.DetailsClass.GetValue(this, global::LightSwitchApplication.Northwind.DetailsClass.PropertySetProperties.Products);
            }
        }
        
        #endregion
    
        #region Queries
    
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="CustomerID">
        /// The value of the 'CustomerID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Customer Customers_Single(string CustomerID)
        {
            return this.Details.Methods.Customers_Single.CreateInvocation(CustomerID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="CustomerID">
        /// The value of the 'CustomerID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Customer Customers_SingleOrDefault(string CustomerID)
        {
            return this.Details.Methods.Customers_SingleOrDefault.CreateInvocation(CustomerID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="EmployeeID">
        /// The value of the 'EmployeeID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Employee Employees_Single(global::System.Nullable<int> EmployeeID)
        {
            return this.Details.Methods.Employees_Single.CreateInvocation(EmployeeID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="EmployeeID">
        /// The value of the 'EmployeeID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Employee Employees_SingleOrDefault(global::System.Nullable<int> EmployeeID)
        {
            return this.Details.Methods.Employees_SingleOrDefault.CreateInvocation(EmployeeID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="ProductID">
        /// The value of the 'ProductID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Product Products_Single(global::System.Nullable<int> ProductID)
        {
            return this.Details.Methods.Products_Single.CreateInvocation(ProductID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="ProductID">
        /// The value of the 'ProductID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Product Products_SingleOrDefault(global::System.Nullable<int> ProductID)
        {
            return this.Details.Methods.Products_SingleOrDefault.CreateInvocation(ProductID).Execute();
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Northwind.DetailsClass.PropertySet, global::LightSwitchApplication.Northwind.DetailsClass.MethodSet>
        {
    
            static DetailsClass()
            {
                var initializeMethodEntry = global::LightSwitchApplication.Northwind.DetailsClass.MethodSetProperties.Customers_Single;
                var initializePropertyEntry = global::LightSwitchApplication.Northwind.DetailsClass.PropertySetProperties.Customers;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.Northwind.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Northwind.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass>
            {
    
                public MethodSet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Customer> Customers_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Northwind.DetailsClass.MethodSetProperties.Customers_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Customer>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Customer> Customers_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Northwind.DetailsClass.MethodSetProperties.Customers_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Customer>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Employee> Employees_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Northwind.DetailsClass.MethodSetProperties.Employees_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Employee>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Employee> Employees_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Northwind.DetailsClass.MethodSetProperties.Employees_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Employee>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Product> Products_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Northwind.DetailsClass.MethodSetProperties.Products_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Product>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Product> Products_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Northwind.DetailsClass.MethodSetProperties.Products_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Product>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Customer> Customers
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Northwind.DetailsClass.PropertySetProperties.Customers) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Customer>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Employee> Employees
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Northwind.DetailsClass.PropertySetProperties.Employees) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Employee>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Product> Products
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Northwind.DetailsClass.PropertySetProperties.Products) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Product>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class MethodSetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Customer>.Entry
                    Customers_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Customer>.Entry(
                        "Customers_Single",
                        global::LightSwitchApplication.Northwind.DetailsClass.MethodSetProperties._Customers_Single_Stub);
                private static void _Customers_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Northwind.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Customer>.Data> c, global::LightSwitchApplication.Northwind.DetailsClass d, object sf)
                {
                    c(d, ref d._Customers_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Customer>.Entry
                    Customers_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Customer>.Entry(
                        "Customers_SingleOrDefault",
                        global::LightSwitchApplication.Northwind.DetailsClass.MethodSetProperties._Customers_SingleOrDefault_Stub);
                private static void _Customers_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Northwind.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Customer>.Data> c, global::LightSwitchApplication.Northwind.DetailsClass d, object sf)
                {
                    c(d, ref d._Customers_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Employee>.Entry
                    Employees_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Employee>.Entry(
                        "Employees_Single",
                        global::LightSwitchApplication.Northwind.DetailsClass.MethodSetProperties._Employees_Single_Stub);
                private static void _Employees_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Northwind.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Employee>.Data> c, global::LightSwitchApplication.Northwind.DetailsClass d, object sf)
                {
                    c(d, ref d._Employees_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Employee>.Entry
                    Employees_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Employee>.Entry(
                        "Employees_SingleOrDefault",
                        global::LightSwitchApplication.Northwind.DetailsClass.MethodSetProperties._Employees_SingleOrDefault_Stub);
                private static void _Employees_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Northwind.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Employee>.Data> c, global::LightSwitchApplication.Northwind.DetailsClass d, object sf)
                {
                    c(d, ref d._Employees_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Product>.Entry
                    Products_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Product>.Entry(
                        "Products_Single",
                        global::LightSwitchApplication.Northwind.DetailsClass.MethodSetProperties._Products_Single_Stub);
                private static void _Products_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Northwind.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Product>.Data> c, global::LightSwitchApplication.Northwind.DetailsClass d, object sf)
                {
                    c(d, ref d._Products_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Product>.Entry
                    Products_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Product>.Entry(
                        "Products_SingleOrDefault",
                        global::LightSwitchApplication.Northwind.DetailsClass.MethodSetProperties._Products_SingleOrDefault_Stub);
                private static void _Products_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Northwind.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Product>.Data> c, global::LightSwitchApplication.Northwind.DetailsClass d, object sf)
                {
                    c(d, ref d._Products_SingleOrDefault, sf);
                }
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Customer>.Entry
                    Customers = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Customer>.Entry(
                        "Customers",
                        global::LightSwitchApplication.Northwind.DetailsClass.PropertySetProperties._Customers_Stub);
                private static void _Customers_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Northwind.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Customer>.Data> c, global::LightSwitchApplication.Northwind.DetailsClass d, object sf)
                {
                    c(d, ref d._Customers, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Employee>.Entry
                    Employees = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Employee>.Entry(
                        "Employees",
                        global::LightSwitchApplication.Northwind.DetailsClass.PropertySetProperties._Employees_Stub);
                private static void _Employees_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Northwind.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Employee>.Data> c, global::LightSwitchApplication.Northwind.DetailsClass d, object sf)
                {
                    c(d, ref d._Employees, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Product>.Entry
                    Products = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Product>.Entry(
                        "Products",
                        global::LightSwitchApplication.Northwind.DetailsClass.PropertySetProperties._Products_Stub);
                private static void _Products_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Northwind.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Product>.Data> c, global::LightSwitchApplication.Northwind.DetailsClass d, object sf)
                {
                    c(d, ref d._Products, sf);
                }
     
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Customer>.Data _Customers;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Employee>.Data _Employees;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Product>.Data _Products;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Customer>.Data _Customers_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Customer>.Data _Customers_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Employee>.Data _Employees_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Employee>.Data _Employees_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Product>.Data _Products_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Northwind, global::LightSwitchApplication.Northwind.DetailsClass, global::LightSwitchApplication.Product>.Data _Products_SingleOrDefault;
            
        }
    
        #endregion
    }
    
    #endregion
    
}
