

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class Product : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Product entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Product()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Product(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Product> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Product.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Product_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Product_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ProductID
        {
            get
            {
                return global::LightSwitchApplication.Product.DetailsClass.GetValue(this, global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.ProductID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ProductName
        {
            get
            {
                return global::LightSwitchApplication.Product.DetailsClass.GetValue(this, global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.ProductName);
            }
            set
            {
                global::LightSwitchApplication.Product.DetailsClass.SetValue(this, global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.ProductName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProductName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> SupplierID
        {
            get
            {
                return global::LightSwitchApplication.Product.DetailsClass.GetValue(this, global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.SupplierID);
            }
            set
            {
                global::LightSwitchApplication.Product.DetailsClass.SetValue(this, global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.SupplierID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SupplierID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SupplierID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SupplierID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> CategoryID
        {
            get
            {
                return global::LightSwitchApplication.Product.DetailsClass.GetValue(this, global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.CategoryID);
            }
            set
            {
                global::LightSwitchApplication.Product.DetailsClass.SetValue(this, global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.CategoryID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CategoryID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CategoryID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CategoryID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string QuantityPerUnit
        {
            get
            {
                return global::LightSwitchApplication.Product.DetailsClass.GetValue(this, global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.QuantityPerUnit);
            }
            set
            {
                global::LightSwitchApplication.Product.DetailsClass.SetValue(this, global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.QuantityPerUnit, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void QuantityPerUnit_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void QuantityPerUnit_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void QuantityPerUnit_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<decimal> UnitPrice
        {
            get
            {
                return global::LightSwitchApplication.Product.DetailsClass.GetValue(this, global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.UnitPrice);
            }
            set
            {
                global::LightSwitchApplication.Product.DetailsClass.SetValue(this, global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.UnitPrice, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UnitPrice_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UnitPrice_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UnitPrice_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<short> UnitsInStock
        {
            get
            {
                return global::LightSwitchApplication.Product.DetailsClass.GetValue(this, global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.UnitsInStock);
            }
            set
            {
                global::LightSwitchApplication.Product.DetailsClass.SetValue(this, global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.UnitsInStock, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UnitsInStock_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UnitsInStock_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UnitsInStock_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<short> UnitsOnOrder
        {
            get
            {
                return global::LightSwitchApplication.Product.DetailsClass.GetValue(this, global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.UnitsOnOrder);
            }
            set
            {
                global::LightSwitchApplication.Product.DetailsClass.SetValue(this, global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.UnitsOnOrder, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UnitsOnOrder_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UnitsOnOrder_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UnitsOnOrder_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<short> ReorderLevel
        {
            get
            {
                return global::LightSwitchApplication.Product.DetailsClass.GetValue(this, global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.ReorderLevel);
            }
            set
            {
                global::LightSwitchApplication.Product.DetailsClass.SetValue(this, global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.ReorderLevel, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ReorderLevel_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ReorderLevel_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ReorderLevel_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Discontinued
        {
            get
            {
                return global::LightSwitchApplication.Product.DetailsClass.GetValue(this, global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.Discontinued);
            }
            set
            {
                global::LightSwitchApplication.Product.DetailsClass.SetValue(this, global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.Discontinued, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Discontinued_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Discontinued_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Discontinued_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Product,
                global::LightSwitchApplication.Product.DetailsClass,
                global::LightSwitchApplication.Product.DetailsClass.IImplementation,
                global::LightSwitchApplication.Product.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.ProductID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass>.Entry
                __ProductEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass>.Entry(
                    global::LightSwitchApplication.Product.DetailsClass.__Product_CreateNew,
                    global::LightSwitchApplication.Product.DetailsClass.__Product_Created,
                    global::LightSwitchApplication.Product.DetailsClass.__Product_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Product __Product_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Product> es)
            {
                return new global::LightSwitchApplication.Product(es);
            }
            private static void __Product_Created(global::LightSwitchApplication.Product e)
            {
                e.Product_Created();
            }
            private static bool __Product_AllowSaveWithErrors(global::LightSwitchApplication.Product e)
            {
                bool result = false;
                e.Product_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Product.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, int> ProductID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.ProductID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, string> ProductName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.ProductName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<int>> SupplierID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.SupplierID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<int>> CategoryID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.CategoryID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, string> QuantityPerUnit
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.QuantityPerUnit) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<decimal>> UnitPrice
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.UnitPrice) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<decimal>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<short>> UnitsInStock
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.UnitsInStock) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<short>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<short>> UnitsOnOrder
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.UnitsOnOrder) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<short>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<short>> ReorderLevel
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.ReorderLevel) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<short>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, bool> Discontinued
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties.Discontinued) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, bool>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int ProductID { get; }
                new string ProductName { get; set; }
                new global::System.Nullable<int> SupplierID { get; set; }
                new global::System.Nullable<int> CategoryID { get; set; }
                new string QuantityPerUnit { get; set; }
                new global::System.Nullable<decimal> UnitPrice { get; set; }
                new global::System.Nullable<short> UnitsInStock { get; set; }
                new global::System.Nullable<short> UnitsOnOrder { get; set; }
                new global::System.Nullable<short> ReorderLevel { get; set; }
                new bool Discontinued { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, int>.Entry
                    ProductID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, int>.Entry(
                        "ProductID",
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._ProductID_Stub,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._ProductID_ComputeIsReadOnly,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._ProductID_Validate,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._ProductID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._ProductID_OnValueChanged);
                private static void _ProductID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Product.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, int>.Data> c, global::LightSwitchApplication.Product.DetailsClass d, object sf)
                {
                    c(d, ref d._ProductID, sf);
                }
                private static bool _ProductID_ComputeIsReadOnly(global::LightSwitchApplication.Product e)
                {
                    bool result = false;
                    e.ProductID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProductID_Validate(global::LightSwitchApplication.Product e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProductID_Validate(r);
                }
                private static int _ProductID_GetImplementationValue(global::LightSwitchApplication.Product.DetailsClass d)
                {
                    return d.ImplementationEntity.ProductID;
                }
                private static void _ProductID_OnValueChanged(global::LightSwitchApplication.Product e)
                {
                    e.ProductID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, string>.Entry
                    ProductName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, string>.Entry(
                        "ProductName",
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._ProductName_Stub,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._ProductName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._ProductName_Validate,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._ProductName_GetImplementationValue,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._ProductName_SetImplementationValue,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._ProductName_OnValueChanged);
                private static void _ProductName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Product.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, string>.Data> c, global::LightSwitchApplication.Product.DetailsClass d, object sf)
                {
                    c(d, ref d._ProductName, sf);
                }
                private static bool _ProductName_ComputeIsReadOnly(global::LightSwitchApplication.Product e)
                {
                    bool result = false;
                    e.ProductName_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProductName_Validate(global::LightSwitchApplication.Product e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProductName_Validate(r);
                }
                private static string _ProductName_GetImplementationValue(global::LightSwitchApplication.Product.DetailsClass d)
                {
                    return d.ImplementationEntity.ProductName;
                }
                private static void _ProductName_SetImplementationValue(global::LightSwitchApplication.Product.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ProductName = v;
                }
                private static void _ProductName_OnValueChanged(global::LightSwitchApplication.Product e)
                {
                    e.ProductName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<int>>.Entry
                    SupplierID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<int>>.Entry(
                        "SupplierID",
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._SupplierID_Stub,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._SupplierID_ComputeIsReadOnly,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._SupplierID_Validate,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._SupplierID_GetImplementationValue,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._SupplierID_SetImplementationValue,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._SupplierID_OnValueChanged);
                private static void _SupplierID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Product.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.Product.DetailsClass d, object sf)
                {
                    c(d, ref d._SupplierID, sf);
                }
                private static bool _SupplierID_ComputeIsReadOnly(global::LightSwitchApplication.Product e)
                {
                    bool result = false;
                    e.SupplierID_IsReadOnly(ref result);
                    return result;
                }
                private static void _SupplierID_Validate(global::LightSwitchApplication.Product e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SupplierID_Validate(r);
                }
                private static global::System.Nullable<int> _SupplierID_GetImplementationValue(global::LightSwitchApplication.Product.DetailsClass d)
                {
                    return d.ImplementationEntity.SupplierID;
                }
                private static void _SupplierID_SetImplementationValue(global::LightSwitchApplication.Product.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.SupplierID = v;
                }
                private static void _SupplierID_OnValueChanged(global::LightSwitchApplication.Product e)
                {
                    e.SupplierID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<int>>.Entry
                    CategoryID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<int>>.Entry(
                        "CategoryID",
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._CategoryID_Stub,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._CategoryID_ComputeIsReadOnly,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._CategoryID_Validate,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._CategoryID_GetImplementationValue,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._CategoryID_SetImplementationValue,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._CategoryID_OnValueChanged);
                private static void _CategoryID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Product.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.Product.DetailsClass d, object sf)
                {
                    c(d, ref d._CategoryID, sf);
                }
                private static bool _CategoryID_ComputeIsReadOnly(global::LightSwitchApplication.Product e)
                {
                    bool result = false;
                    e.CategoryID_IsReadOnly(ref result);
                    return result;
                }
                private static void _CategoryID_Validate(global::LightSwitchApplication.Product e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CategoryID_Validate(r);
                }
                private static global::System.Nullable<int> _CategoryID_GetImplementationValue(global::LightSwitchApplication.Product.DetailsClass d)
                {
                    return d.ImplementationEntity.CategoryID;
                }
                private static void _CategoryID_SetImplementationValue(global::LightSwitchApplication.Product.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.CategoryID = v;
                }
                private static void _CategoryID_OnValueChanged(global::LightSwitchApplication.Product e)
                {
                    e.CategoryID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, string>.Entry
                    QuantityPerUnit = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, string>.Entry(
                        "QuantityPerUnit",
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._QuantityPerUnit_Stub,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._QuantityPerUnit_ComputeIsReadOnly,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._QuantityPerUnit_Validate,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._QuantityPerUnit_GetImplementationValue,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._QuantityPerUnit_SetImplementationValue,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._QuantityPerUnit_OnValueChanged);
                private static void _QuantityPerUnit_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Product.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, string>.Data> c, global::LightSwitchApplication.Product.DetailsClass d, object sf)
                {
                    c(d, ref d._QuantityPerUnit, sf);
                }
                private static bool _QuantityPerUnit_ComputeIsReadOnly(global::LightSwitchApplication.Product e)
                {
                    bool result = false;
                    e.QuantityPerUnit_IsReadOnly(ref result);
                    return result;
                }
                private static void _QuantityPerUnit_Validate(global::LightSwitchApplication.Product e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.QuantityPerUnit_Validate(r);
                }
                private static string _QuantityPerUnit_GetImplementationValue(global::LightSwitchApplication.Product.DetailsClass d)
                {
                    return d.ImplementationEntity.QuantityPerUnit;
                }
                private static void _QuantityPerUnit_SetImplementationValue(global::LightSwitchApplication.Product.DetailsClass d, string v)
                {
                    d.ImplementationEntity.QuantityPerUnit = v;
                }
                private static void _QuantityPerUnit_OnValueChanged(global::LightSwitchApplication.Product e)
                {
                    e.QuantityPerUnit_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<decimal>>.Entry
                    UnitPrice = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<decimal>>.Entry(
                        "UnitPrice",
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._UnitPrice_Stub,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._UnitPrice_ComputeIsReadOnly,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._UnitPrice_Validate,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._UnitPrice_GetImplementationValue,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._UnitPrice_SetImplementationValue,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._UnitPrice_OnValueChanged);
                private static void _UnitPrice_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Product.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<decimal>>.Data> c, global::LightSwitchApplication.Product.DetailsClass d, object sf)
                {
                    c(d, ref d._UnitPrice, sf);
                }
                private static bool _UnitPrice_ComputeIsReadOnly(global::LightSwitchApplication.Product e)
                {
                    bool result = false;
                    e.UnitPrice_IsReadOnly(ref result);
                    return result;
                }
                private static void _UnitPrice_Validate(global::LightSwitchApplication.Product e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.UnitPrice_Validate(r);
                }
                private static global::System.Nullable<decimal> _UnitPrice_GetImplementationValue(global::LightSwitchApplication.Product.DetailsClass d)
                {
                    return d.ImplementationEntity.UnitPrice;
                }
                private static void _UnitPrice_SetImplementationValue(global::LightSwitchApplication.Product.DetailsClass d, global::System.Nullable<decimal> v)
                {
                    d.ImplementationEntity.UnitPrice = v;
                }
                private static void _UnitPrice_OnValueChanged(global::LightSwitchApplication.Product e)
                {
                    e.UnitPrice_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<short>>.Entry
                    UnitsInStock = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<short>>.Entry(
                        "UnitsInStock",
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._UnitsInStock_Stub,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._UnitsInStock_ComputeIsReadOnly,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._UnitsInStock_Validate,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._UnitsInStock_GetImplementationValue,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._UnitsInStock_SetImplementationValue,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._UnitsInStock_OnValueChanged);
                private static void _UnitsInStock_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Product.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<short>>.Data> c, global::LightSwitchApplication.Product.DetailsClass d, object sf)
                {
                    c(d, ref d._UnitsInStock, sf);
                }
                private static bool _UnitsInStock_ComputeIsReadOnly(global::LightSwitchApplication.Product e)
                {
                    bool result = false;
                    e.UnitsInStock_IsReadOnly(ref result);
                    return result;
                }
                private static void _UnitsInStock_Validate(global::LightSwitchApplication.Product e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.UnitsInStock_Validate(r);
                }
                private static global::System.Nullable<short> _UnitsInStock_GetImplementationValue(global::LightSwitchApplication.Product.DetailsClass d)
                {
                    return d.ImplementationEntity.UnitsInStock;
                }
                private static void _UnitsInStock_SetImplementationValue(global::LightSwitchApplication.Product.DetailsClass d, global::System.Nullable<short> v)
                {
                    d.ImplementationEntity.UnitsInStock = v;
                }
                private static void _UnitsInStock_OnValueChanged(global::LightSwitchApplication.Product e)
                {
                    e.UnitsInStock_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<short>>.Entry
                    UnitsOnOrder = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<short>>.Entry(
                        "UnitsOnOrder",
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._UnitsOnOrder_Stub,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._UnitsOnOrder_ComputeIsReadOnly,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._UnitsOnOrder_Validate,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._UnitsOnOrder_GetImplementationValue,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._UnitsOnOrder_SetImplementationValue,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._UnitsOnOrder_OnValueChanged);
                private static void _UnitsOnOrder_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Product.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<short>>.Data> c, global::LightSwitchApplication.Product.DetailsClass d, object sf)
                {
                    c(d, ref d._UnitsOnOrder, sf);
                }
                private static bool _UnitsOnOrder_ComputeIsReadOnly(global::LightSwitchApplication.Product e)
                {
                    bool result = false;
                    e.UnitsOnOrder_IsReadOnly(ref result);
                    return result;
                }
                private static void _UnitsOnOrder_Validate(global::LightSwitchApplication.Product e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.UnitsOnOrder_Validate(r);
                }
                private static global::System.Nullable<short> _UnitsOnOrder_GetImplementationValue(global::LightSwitchApplication.Product.DetailsClass d)
                {
                    return d.ImplementationEntity.UnitsOnOrder;
                }
                private static void _UnitsOnOrder_SetImplementationValue(global::LightSwitchApplication.Product.DetailsClass d, global::System.Nullable<short> v)
                {
                    d.ImplementationEntity.UnitsOnOrder = v;
                }
                private static void _UnitsOnOrder_OnValueChanged(global::LightSwitchApplication.Product e)
                {
                    e.UnitsOnOrder_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<short>>.Entry
                    ReorderLevel = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<short>>.Entry(
                        "ReorderLevel",
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._ReorderLevel_Stub,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._ReorderLevel_ComputeIsReadOnly,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._ReorderLevel_Validate,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._ReorderLevel_GetImplementationValue,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._ReorderLevel_SetImplementationValue,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._ReorderLevel_OnValueChanged);
                private static void _ReorderLevel_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Product.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<short>>.Data> c, global::LightSwitchApplication.Product.DetailsClass d, object sf)
                {
                    c(d, ref d._ReorderLevel, sf);
                }
                private static bool _ReorderLevel_ComputeIsReadOnly(global::LightSwitchApplication.Product e)
                {
                    bool result = false;
                    e.ReorderLevel_IsReadOnly(ref result);
                    return result;
                }
                private static void _ReorderLevel_Validate(global::LightSwitchApplication.Product e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ReorderLevel_Validate(r);
                }
                private static global::System.Nullable<short> _ReorderLevel_GetImplementationValue(global::LightSwitchApplication.Product.DetailsClass d)
                {
                    return d.ImplementationEntity.ReorderLevel;
                }
                private static void _ReorderLevel_SetImplementationValue(global::LightSwitchApplication.Product.DetailsClass d, global::System.Nullable<short> v)
                {
                    d.ImplementationEntity.ReorderLevel = v;
                }
                private static void _ReorderLevel_OnValueChanged(global::LightSwitchApplication.Product e)
                {
                    e.ReorderLevel_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, bool>.Entry
                    Discontinued = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, bool>.Entry(
                        "Discontinued",
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._Discontinued_Stub,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._Discontinued_ComputeIsReadOnly,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._Discontinued_Validate,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._Discontinued_GetImplementationValue,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._Discontinued_SetImplementationValue,
                        global::LightSwitchApplication.Product.DetailsClass.PropertySetProperties._Discontinued_OnValueChanged);
                private static void _Discontinued_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Product.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, bool>.Data> c, global::LightSwitchApplication.Product.DetailsClass d, object sf)
                {
                    c(d, ref d._Discontinued, sf);
                }
                private static bool _Discontinued_ComputeIsReadOnly(global::LightSwitchApplication.Product e)
                {
                    bool result = false;
                    e.Discontinued_IsReadOnly(ref result);
                    return result;
                }
                private static void _Discontinued_Validate(global::LightSwitchApplication.Product e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Discontinued_Validate(r);
                }
                private static bool _Discontinued_GetImplementationValue(global::LightSwitchApplication.Product.DetailsClass d)
                {
                    return d.ImplementationEntity.Discontinued;
                }
                private static void _Discontinued_SetImplementationValue(global::LightSwitchApplication.Product.DetailsClass d, bool v)
                {
                    d.ImplementationEntity.Discontinued = v;
                }
                private static void _Discontinued_OnValueChanged(global::LightSwitchApplication.Product e)
                {
                    e.Discontinued_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, int>.Data _ProductID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, string>.Data _ProductName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<int>>.Data _SupplierID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<int>>.Data _CategoryID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, string>.Data _QuantityPerUnit;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<decimal>>.Data _UnitPrice;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<short>>.Data _UnitsInStock;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<short>>.Data _UnitsOnOrder;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, global::System.Nullable<short>>.Data _ReorderLevel;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass, bool>.Data _Discontinued;
            
        }
    
        #endregion
    }
    
    #endregion
}
